# Default configuration for the auth service.
# Values can be overridden by environment variables or command-line flags.

server:
  # The port the server will listen on.
  # Env: AUTH_SERVER_PORT
  port: ":8082"

database:
  # Path to the SQLite database file.
  # Env: AUTHN_DATABASE_PATH
  path: "./authn.db"
  
  # MongoDB connection string.
  # Env: AUTHN_DATABASE_MONGO_URL
  mongo_url: "${AUTHN_DATABASE_MONGO_URL:-mongodb://localhost:27017}"
  
  # MongoDB database name.
  # Env: AUTHN_DATABASE_MONGO_DATABASE  
  mongo_database: "${AUTHN_DATABASE_MONGO_DATABASE:-authn}"

auth:
  # AES-GCM encryption key for PII data (32 bytes).
  # Env: AUTH_ENCRYPTION_KEY
  encryption_key: "12345678901234567890123456789012"
  
  # HMAC signing key for lookup hashes.
  # Env: AUTH_SIGNING_KEY  
  signing_key: "change-me-signing-key-for-hmac"
  
  # Session TTL duration.
  # Env: AUTH_SESSION_TTL
  session_ttl: "24h"
  
  # RSA private key for token signing (PEM format).
  # Env: AUTH_TOKEN_PRIVATE_KEY
  token_private_key: ""
  
  # RSA public key for token verification (PEM format).
  # Env: AUTH_TOKEN_PUBLIC_KEY  
  token_public_key: ""

log:
  level: "info"

debug:
  routes: true
