# Default configuration for the service.
# Values can be overridden by environment variables or command-line flags.

server:
  # The port the server will estateen on.
  # Env: ESTATE_SERVER_PORT
  port: ":8084"

database:
  # Path to the SQLite database file.
  # Env: ESTATE_DATABASE_PATH
  path: "./app.db"

  # MongoDB connection string.
  # Env: ESTATE_DATABASE_MONGO_URL
  mongo_url: "mongodb://admin:password@localhost:27017/estate?authSource=admin"

  # MongoDB database name.
  # Env: ESTATE_DATABASE_MONGO_DATABASE
  mongo_database: "estate"

log:
  level: "info"

debug:
  routes: true
